spring.application.name=acabou-mony-notificacao
server.port=8087

# Banco de Dados Único do Ecossistema
spring.datasource.url=jdbc:mysql://localhost:3306/db_acabou_mony?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:solutis}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Infraestrutura RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


sendgrid.api-key=SG
sendgrid.from-email=gustavomunizoliveira07@gmail.com

spring.mvc.converters.preferred-json-mapper=jackson