server.port=8088
jwt.secret=nhfc6HAxsZSzhyqZrVd7ANzR8zKLh2+u9gac7Mc3MCqcDoVZzQyXqzZYEKFXCoP9l6gkpi+VDiEZtD3eBBf4Eg==

services.auth.url=http://127.0.0.1:8081
services.account.url=http://127.0.0.1:8080
services.card.url=http://127.0.0.1:8085
services.transaction.url=http://127.0.0.1:8083
services.auditing.url=http://127.0.0.1:8084
